/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DonateRouteImport } from './routes/donate'
import { Route as DonorsRouteImport } from './routes/donors'
import { Route as RequestBloodRouteImport } from './routes/request-blood'
import { Route as RequestsRouteImport } from './routes/requests'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DonateRoute = DonateRouteImport.update({
  id: '/donate',
  path: '/donate',
  getParentRoute: () => rootRouteImport,
} as any)
const DonorsRoute = DonorsRouteImport.update({
  id: '/donors',
  path: '/donors',
  getParentRoute: () => rootRouteImport,
} as any)
const RequestBloodRoute = RequestBloodRouteImport.update({
  id: '/request-blood',
  path: '/request-blood',
  getParentRoute: () => rootRouteImport,
} as any)
const RequestsRoute = RequestsRouteImport.update({
  id: '/requests',
  path: '/requests',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/donate': typeof DonateRoute
  '/donors': typeof DonorsRoute
  '/request-blood': typeof RequestBloodRoute
  '/requests': typeof RequestsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/donate': typeof DonateRoute
  '/donors': typeof DonorsRoute
  '/request-blood': typeof RequestBloodRoute
  '/requests': typeof RequestsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/donate': typeof DonateRoute
  '/donors': typeof DonorsRoute
  '/request-blood': typeof RequestBloodRoute
  '/requests': typeof RequestsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/donate' | '/donors' | '/request-blood' | '/requests'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/donate' | '/donors' | '/request-blood' | '/requests'
  id: '__root__' | '/' | '/donate' | '/donors' | '/request-blood' | '/requests'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DonateRoute: typeof DonateRoute
  DonorsRoute: typeof DonorsRoute
  RequestBloodRoute: typeof RequestBloodRoute
  RequestsRoute: typeof RequestsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/donate': {
      id: '/donate'
      path: '/donate'
      fullPath: '/donate'
      preLoaderRoute: typeof DonateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/donors': {
      id: '/donors'
      path: '/donors'
      fullPath: '/donors'
      preLoaderRoute: typeof DonorsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/request-blood': {
      id: '/request-blood'
      path: '/request-blood'
      fullPath: '/request-blood'
      preLoaderRoute: typeof RequestBloodRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/requests': {
      id: '/requests'
      path: '/requests'
      fullPath: '/requests'
      preLoaderRoute: typeof RequestsRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DonateRoute: DonateRoute,
  DonorsRoute: DonorsRoute,
  RequestBloodRoute: RequestBloodRoute,
  RequestsRoute: RequestsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
